export const getLanguageFromExtension = (fileExtension: string) => {
  switch (fileExtension) {
    case "js":
      return "javascript";
    case "jsx":
      return "javascriptreact";
    case "vue":
      return "vue";
    case "ts":
      return "typescript";
    case "tsx":
      return "typescriptreact";
    case "css":
      return "css";
    case "html":
      return "html";
    case "md":
      return "markdown";
    case "py":
      return "python";
    case "java":
      return "java";
    case "cpp":
    case "cc":
    case "cxx":
      return "cpp";
    case "c":
      return "c";
    case "cs":
      return "csharp";
    case "go":
      return "go";
    case "rb":
      return "ruby";
    case "php":
      return "php";
    case "swift":
      return "swift";
    case "m":
      return "objective-c";
    case "sh":
      return "bash";
    case "sql":
      return "sql";
    case "xml":
      return "xml";
    case "yaml":
    case "yml":
      return "yaml";
    case "json":
      return "json";
    case "astro":
      return "plaintext";
    case "scss":
      return "scss";
    default:
      return "javascript";
  }
};
